import '../styles/index.scss';

console.log('webpack starterkit');
/*
const corridasWeb = [
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "5 - TRANSPORTES CHIHUAHUENSES, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "TCH",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500802",
      "fechaInicioVigencia": "20191202",
      "fechaLlegada": 20210504,
      "horaCorrida": "0600",
      "horaLlegada": "0845",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "marcaComercial": "TCH",
      "numeroCorrida": "1366",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "33832",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 350,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "102-106",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "9 - AUTOBUSES EXPRESO FUTURA, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "AEF",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500515",
      "fechaInicioVigencia": "20190429",
      "fechaLlegada": 20210504,
      "horaCorrida": "0700",
      "horaLlegada": "0950",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "AEF",
      "numeroCorrida": "2122",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "4565",
      "salaSalida": "2",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "102-107",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "71 - AUTOBUSES POBLANOS DEL CENTRO, S. A. DE C. V.",
      "descripcionServicio": "PRIMERA LUJO",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "APO",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500703",
      "fechaInicioVigencia": "20191213",
      "fechaLlegada": 20210504,
      "horaCorrida": "0730",
      "horaLlegada": "1015",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "marcaComercial": "AEF",
      "numeroCorrida": "7118",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "16938",
      "salaSalida": "2",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 350,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "03",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "104",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "9 - AUTOBUSES EXPRESO FUTURA, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "AEF",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20200417",
      "fechaInicioVigencia": "20181213",
      "fechaLlegada": 20210504,
      "horaCorrida": "0800",
      "horaLlegada": "1040",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "AEF",
      "numeroCorrida": "50067",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "17351",
      "salaSalida": "2",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "102-106",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "9 - AUTOBUSES EXPRESO FUTURA, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "AEF",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500515",
      "fechaInicioVigencia": "20190429",
      "fechaLlegada": 20210504,
      "horaCorrida": "0900",
      "horaLlegada": "1150",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "AEF",
      "numeroCorrida": "2003",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "4509",
      "salaSalida": "2",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "35 - TRANSPORTES DEL PACIFICO, SA DE CV",
      "descripcionServicio": "ECONOMICO",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "TDP",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500821",
      "fechaInicioVigencia": "20170817",
      "fechaLlegada": 20210504,
      "horaCorrida": "0930",
      "horaLlegada": "1215",
      "ivaAdulto": 38.62,
      "ivaAdultoMix": 0,
      "ivaCompleto": 38.62,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 19.31,
      "ivaEstudianteMix": 0,
      "ivaInpam": 19.31,
      "ivaInpamMix": 0,
      "ivaMaestro": 28.97,
      "ivaMaestroMix": 0,
      "ivaNinio": 19.31,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        }
      ],
      "marcaComercial": "TDP",
      "numeroCorrida": "20558",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "20937",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 241.38,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 241.38,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 120.69,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 120.69,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 181.03,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 120.69,
      "subtotalNinioMix": 0,
      "tarifa": 280,
      "tarifaAdulto": 224,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 140,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 140,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 210,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 140,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "01",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "19 - AUTOBUSES INTERESTATALES DE  MEXICO, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "AIM",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20501231",
      "fechaInicioVigencia": "20200107",
      "fechaLlegada": 20210504,
      "horaCorrida": "1000",
      "horaLlegada": "1250",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "AIS",
      "numeroCorrida": "309",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "33245",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "48",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 48,
      "descripcionEmpresa": "8 - TRANSPORTES FRONTERA, S.A. DE C.V.",
      "descripcionServicio": "ECONOMICO",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "TFR",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20410630",
      "fechaInicioVigencia": "20190627",
      "fechaLlegada": 20210504,
      "horaCorrida": "1000",
      "horaLlegada": "1315",
      "ivaAdulto": 38.62,
      "ivaAdultoMix": 0,
      "ivaCompleto": 38.62,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 19.31,
      "ivaEstudianteMix": 0,
      "ivaInpam": 19.31,
      "ivaInpamMix": 0,
      "ivaMaestro": 28.97,
      "ivaMaestroMix": 0,
      "ivaNinio": 19.31,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        }
      ],
      "marcaComercial": "TFR",
      "numeroCorrida": "15245",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "29319",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 241.38,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 241.38,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 120.69,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 120.69,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 181.03,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 120.69,
      "subtotalNinioMix": 0,
      "tarifa": 280,
      "tarifaAdulto": 224,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 140,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 140,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 210,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 140,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "01",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "5 - TRANSPORTES CHIHUAHUENSES, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "TCH",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500802",
      "fechaInicioVigencia": "20191202",
      "fechaLlegada": 20210504,
      "horaCorrida": "1000",
      "horaLlegada": "1245",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "TCH",
      "numeroCorrida": "1101",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "33832",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "79 - OPERADORA AUTOTRANSPORTES ANAHUAC DE COAHUILA, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "APA",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500703",
      "fechaInicioVigencia": "20191212",
      "fechaLlegada": 20210504,
      "horaCorrida": "1300",
      "horaLlegada": "1550",
      "ivaAdulto": 44.83,
      "ivaAdultoMix": 0,
      "ivaCompleto": 44.83,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 22.41,
      "ivaEstudianteMix": 0,
      "ivaInpam": 22.41,
      "ivaInpamMix": 0,
      "ivaMaestro": 33.59,
      "ivaMaestroMix": 0,
      "ivaNinio": 22.41,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 325,
          "precioConDescuento": 260
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 325,
          "precioConDescuento": 260
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 325,
          "precioConDescuento": 260
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 325,
          "precioConDescuento": 260
        }
      ],
      "marcaComercial": "24",
      "numeroCorrida": "97687",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "30786",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 280.17,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 280.17,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 140.09,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 140.09,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 209.91,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 140.09,
      "subtotalNinioMix": 0,
      "tarifa": 325,
      "tarifaAdulto": 260,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 162.5,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 162.5,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 243.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 162.5,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "02",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "35 - TRANSPORTES DEL PACIFICO, SA DE CV",
      "descripcionServicio": "ECONOMICO",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "TDP",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500821",
      "fechaInicioVigencia": "20170817",
      "fechaLlegada": 20210504,
      "horaCorrida": "1330",
      "horaLlegada": "1620",
      "ivaAdulto": 38.62,
      "ivaAdultoMix": 0,
      "ivaCompleto": 38.62,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 19.31,
      "ivaEstudianteMix": 0,
      "ivaInpam": 19.31,
      "ivaInpamMix": 0,
      "ivaMaestro": 28.97,
      "ivaMaestroMix": 0,
      "ivaNinio": 19.31,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 280,
          "precioConDescuento": 224
        }
      ],
      "marcaComercial": "TDP",
      "numeroCorrida": "440",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "33549",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 241.38,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 241.38,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 120.69,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 120.69,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 181.03,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 120.69,
      "subtotalNinioMix": 0,
      "tarifa": 280,
      "tarifaAdulto": 224,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 140,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 140,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 210,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 140,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "01",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "5 - TRANSPORTES CHIHUAHUENSES, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "TCH",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500802",
      "fechaInicioVigencia": "20191202",
      "fechaLlegada": 20210504,
      "horaCorrida": "1600",
      "horaLlegada": "1845",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "TCH",
      "numeroCorrida": "1115",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "33832",
      "salaSalida": "",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "83 AL 87",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "19 - AUTOBUSES INTERESTATALES DE  MEXICO, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "L",
      "dispositivoGeneral": "1",
      "empresa": "AIM",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20501015",
      "fechaInicioVigencia": "20190806",
      "fechaLlegada": 20210504,
      "horaCorrida": "1600",
      "horaLlegada": "1845",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "AIS",
      "numeroCorrida": "396",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0001",
      "oficinaCorrida": "0001",
      "oficinaDestino": "0010",
      "ruta": "13371",
      "salaSalida": "4",
      "secuencia": 10,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "L",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "MXN",
      "ubicacionCorrida": "MXN",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    },
    {
      "error": "Exitoso",
      "respuesta": 1,
      "solicitud": "20210429164720611",
      "andenSalida": "",
      "codigo": "",
      "cupoAdulto": "36",
      "cupoAdultoMix": "00",
      "cupoEstudiante": "00",
      "cupoEstudianteMix": "00",
      "cupoInapam": "08",
      "cupoInapamMix": "00",
      "cupoMaestro": "00",
      "cupoMaestroMix": "00",
      "cupoNinio": "08",
      "cupoNinioMix": "00",
      "cupoWeb": 36,
      "descripcionEmpresa": "5 - TRANSPORTES CHIHUAHUENSES, S.A. DE C.V.",
      "descripcionServicio": "PRIMERA SELECT",
      "directoParadas": "P",
      "dispositivoGeneral": "1",
      "empresa": "TCH",
      "empresaFrontera": "",
      "fechaCorrida": "20210504",
      "fechaDesafasamiento": "20210504",
      "fechaFinVigencia": "20500802",
      "fechaInicioVigencia": "20191202",
      "fechaLlegada": 20210504,
      "horaCorrida": "2000",
      "horaLlegada": "2255",
      "ivaAdulto": 48.28,
      "ivaAdultoMix": 0,
      "ivaCompleto": 48.28,
      "ivaCompletoMix": 0,
      "ivaEstudiante": 24.14,
      "ivaEstudianteMix": 0,
      "ivaInpam": 24.14,
      "ivaInpamMix": 0,
      "ivaMaestro": 36.21,
      "ivaMaestroMix": 0,
      "ivaNinio": 24.14,
      "ivaNinioMix": 0,
      "listaDescuentos": [
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        },
        {
          "cantidadAsientos": 4,
          "porcentajeDescuento": 20,
          "precioBase": 350,
          "precioConDescuento": 280
        }
      ],
      "marcaComercial": "TCH",
      "numeroCorrida": "110451",
      "ocupacion": "",
      "oficinaClaveOrigen": "0001",
      "oficinaClavefrontera": "",
      "oficinaControl": "0705",
      "oficinaCorrida": "0705",
      "oficinaDestino": "0010",
      "ruta": "34430",
      "salaSalida": "",
      "secuencia": 40,
      "subtotalAdulto": 301.72,
      "subtotalAdultoMix": 0,
      "subtotalCompleto": 301.72,
      "subtotalCompletoMix": 0,
      "subtotalEstudiante": 150.86,
      "subtotalEstudianteMix": 0,
      "subtotalInpam": 150.86,
      "subtotalInpamMix": 0,
      "subtotalMaestro": 226.29,
      "subtotalMaestroMix": 0,
      "subtotalNinio": 150.86,
      "subtotalNinioMix": 0,
      "tarifa": 350,
      "tarifaAdulto": 280,
      "tarifaAdultoMix": 0,
      "tarifaCompletoMix": 0,
      "tarifaEstudiante": 175,
      "tarifaEstudianteMix": 0,
      "tarifaInapam": 175,
      "tarifaInapamMix": 0,
      "tarifaMaestro": 262.5,
      "tarifaMaestroMix": 0,
      "tarifaNinio": 175,
      "tarifaNinioMix": 0,
      "tipoCorrida": "P",
      "tipoItinerario": "I",
      "tipoServicio": "09",
      "tipoServicioMix": "0",
      "ubicacionControl": "ACA",
      "ubicacionCorrida": "ACA",
      "zonaHorariaDestino": "Mexico/General",
      "zonaHorariaOrigen": "Mexico/General"
    }
  ]


/*
  Crear una funcion que reciba como parametros empresa y descripcion de servicio. 

  * La funcion debe buscar en la constante corridasWeb las corridas que coincidan con los parametros enviados en la función.
  
  * El parametro empresa debe ser opcional y en caso de no enviarlo asignar como default el valor "AEF"
  
  * La funcion debe regresar un arreglo de objetos de tipo corrida con los siguientes atributos.
   - numeroCorrida. String
   - descripcionServicio. String
   - empresa. String
   - descripcionEmpresa: String
   - tienePromoción. Boolean. Deberá ir en true en caso de que una de las corridas web tenga lista de descuetos "listaDescuentos"
   
  * En caso de no encontrar corridas, regresar un error con el mensaje "No hay corridas disponibles"
  
*/

/*
function empresa(descripcion,empresa='AEF'){

        
        let buscaempresa=corridasWeb.filter(v=> v.empresa===empresa);
        let buscadescripcion=corridasWeb.filter(v=>v.descripcionServicio===descripcion);
        
        console.log(buscaempresa,buscadescripcion);
}

empresa('PRIMERA SELECT');

*/



//Ejercicio 2

const directory=[
  {
    "id": "1",
    "email": "ricardo.jimenez@axity.com"
  },
  {
    "id": "2",
    "email": "jesus.avila@axity.com"
  },
  {
    "id": "3",
    "email": "rocio.esteban@axity.com"
  },
  {
    "id": "4",
    "email": "laura.perez@axity.com"
  },
  {
    "id": "5",
    "email": "francisco.hernandez@axity.com"
  },
  {
    "id": "6",
    "email": "carlos.juarez@axity.com"
  },
  {
    "id": "7",
    "email": "javier.hernandez@axity.com"
  },{
    "id": "8",
    "email": "elizabeth.contreras@axity.com"
  }
];

const users = [
  {
    "id": "1",
    "name": "Ricardo",
    "lastName": "Jimenez",
    "email": "ricardo.jimenez@axity.com",
    "yearBirth": "1988",
    "monthBirth": "03",
    "dayBirth": "05",
    "status": "active"
  },
  {
    "id": "2",
    "name": "Jesus",
    "lastName": "Avila",
    "email": "jesus.avila@axity.com",
    "yearBirth": "1989",
    "monthBirth": "02",
    "dayBirth": "04",
    "status": "active"
  },
  {
    "id": "3",
    "name": "Rocio",
    "lastName": "Esteban",
    "email": "rocio.esteban@axity.com",
    "yearBirth": "1987",
    "monthBirth": "01",
    "dayBirth": "03",
    "status": "active"
  },
  {
    "id": "4",
    "name": "Laura",
    "lastName": "Perez",
    "email": "laura.perez@axity.com",
    "yearBirth": "1990",
    "monthBirth": "01",
    "dayBirth": "23",
    "status": "active"
  },
  {
    "id": "5",
    "name": "Francisco",
    "lastName": "Hernadez",
    "email": "francisco.hernandez@axity.com",
    "yearBirth": "1963",
    "monthBirth": "04",
    "dayBirth": "04",
    "status": "active"
  },
  {
    "id": "6",
    "name": "Carlos",
    "lastName": "Juarez",
    "email": "carlos.juarez@axity.com",
    "yearBirth": "1992",
    "monthBirth": "10",
    "dayBirth": "29",
    "status": "active"
  },
  {
    "id": "7",
    "name": "Javier",
    "lastName": "Hernandez",
    "email": "javier.hernandez@axity.com",
    "yearBirth": "1985",
    "monthBirth": "05",
    "dayBirth": "19",
    "status": "false"
  },{
    "id": "8",
    "name": "Elizabeth",
    "lastName": "Contreras",
    "email": "elizabeth.contreras@axity.com",
    "yearBirth": "1984",
    "monthBirth": "10",
    "dayBirth": "29",
    "status": "active"
  }
];

/*
Crear una clase llamada User que implemente una interface llamada IUser con una funcion que devuelva un objeto usuario.

La funcion debe tener las siguientes consideraciones.
* Recibir como parametro un correo.
* Buscar en la constante directory el correo y devolver el id.
* Con el id que se haya obtenido de la constante directory. Buscar en la constante users el usurio con ese mismo id.
* El objeto user debe contener los siguienres atributos
- id
- name. name + lastName
- dateBirth. en formato dd/mm/yyyy
- yearsOld. Calcular a partir de la fecha, del día, del mes y del año de nacimiento
*/
/*
let ids=directory.map(f=>{
    return f.id;
});
console.log(ids);*/
const obtenerCorreo=email=>{
        if(directory.filter(v=>email===v.email)){
            let ids=directory.filter(f=>{
                return f.id;
            });
            console.log("El correo existe ",ids.id);
            obtenerId(ids.id);
        }else console.log("El correo no existe");
    
}
const obtenerId=id=>{
        if(users.find(v=>id===v.id)){
            console.log("El usuario existe", usuarios);
        }else console.log("El usuario no existe");
}
obtenerCorreo("rocio.esteban@axity.com");



